# Growth accounting {#GA}

-------------------------------------------------------------------------------------

In this chapter, we will present the *growth accounting* technique to decompose GDP  and labour productivity growth into different components.

We will use data from the <a href="https://www.rug.nl/ggdc/productivity/pwt/" target="_blank">*Penn World Table*</a> [@PWT], which allow us to compare *real* economic outcomes over time and across countries. All macroeconomic outcomes described, such as GDP, and capital stock, are real outcomes although this may not be explicitly mentioned for simplicity in the text.

-------------------------------------------------------------------------------------

## Introduction

## Growth accounting equation

**TBA**

## Case study: South Korea (1953-2019)

**TBA**

## Exercise (Week 14)

This exercise guides  you through the growth accounting decomposition of UK labour productivity as seen in the lecture slides in week 13, then ask you to do the same for US labour productivity and to finally compare the results for the two countries.

In order to perform these practice questions, you need to work on a laptop or a desktop computer (if possible using a mouse), **not** a tablet. You also need to have installed Excel on your device (you may not be able to perform all the operations using the web version).

### Part 1: Preliminaries{-}

1. Download and learn more about the *Penn World Table* database by checking the information on this website: [PWT](https://www.rug.nl/ggdc/productivity/pwt). [*You may also look up this prompt in Copilot: "Explain what the Penn World Table data is, what is its significance, who is responsible for it and what are its objectives".*]

1. If you have not done so already, go through the [<span style="color: blue;">**Penn World Table in Excel**</span>](https://mp16445.github.io/EXCEL_PWT/) tutorial (click on  blue link to access it) which shows how to perform basic operations and growth accounting using the *Penn World Table* dataset in Excel and make sure you are able to replicate the results.


### Part 2: Describing long-run trends in productivity {-}


1. Create a new Excel sheet with the following variables for the **United Kingdom**: "rgdpna", "rnna", "emp", "avh" and "labsh". Check the variable definitions in the "Legend" sheet.

1. In a new column, create a new variable for labour productivity labelled "y" using "rgdpna", "emp" and "avh". Then create the (natural) logarithm of this variable, labelled "lny". 

1. Make a plot of the logarithm of UK labour productivity. You may add a trendline and its equation. Can you identify the three subperiods described in the week 13 slides?

1. Repeat 1 to 3 using data for the **United States**. Compare the trends in labour productivity growth in the two countries.

 
*Note*: Table 1 (p 3154) *in* Feenstra et al. (<a href="https://www.rug.nl/ggdc/docs/the_next_generation_of_the_penn_world_table.pdf" target="_blank"><span style="color: blue;">link</span></a>) explains why "rgdpna" is the appropriate real GDP variable to study the growth of GDP over time in a single country.

### Part 3: Growth accounting decompositions {-}

In this part, you will perform the growth accounting decomposition of labour productivity growth in the UK and the US. We will use the following growth accounting equation:
$$ g_y = g_A + \beta g_k  $$
where $g_y$ is the growth rate of labour productivity, $g_k$ is the growth rate of the capital-labour ratio, $g_A$ is the growth rate of total factor productivity and $\beta$ is the elasticity of output with respect to capital. We will assume that $\beta = 0.3$ initially.

**Annual growth accounting decompositions**:

1. In a new column, create a new variable for the capital-labour ratio (capital per hour worked) labelled "k" using "rnna", "emp" and "avh". 

1. In two new columns, create the annual growth rate of "y" (labelled "gy") and the annual growth rate of "k" (labelled "gk"). 

1. In two new columns, create the annual contribution of capital accumulation (labelled "bgk") by multiplying "gk" by $\beta = 0.3$ in each year and the annual growth rate of total factor productivity (labelled "gA") as the residual from the growth accounting equation: $g_A = g_y - \beta g_k$.

1. Make a line plot of "gy", "bgk" and "gA" and interpret the results. 


**Growth accounting decompositions over intervals of time**:

In Excel, construct a table as in the Excel tutorial - Section 7.4 containing the full sample period and each subperiod identified in Part 2 in each row.

*Hint*: use the compound growth rate formula, $g_{x,t-s} = \left(\frac{x_t}{x_s}\right)^{\frac{1}{s-t}}-1$, to calculate average growth rates between any two periods $t$ and $s$ in this exercise.


1. Column 1: calculate the average annual growth rate of UK labour productivity ($g_y$) over the full sample period and over each subperiod. 

1. Column 2: calculate the average annual growth rate of the UK capital-labour ($g_k$) over the full sample period and over each subperiod. 

1. Column 3: calculate the contribution of capital accumulation to UK labour productivity ($\beta g_k$) over the full sample period and over each subperiod. 

1. Column 4: calculate the contribution of TFP growth to UK labour productivity ($g_A$) over the full sample period and over each subperiod as the residual of the growth accounting equation: $g_A = g_y - \beta g_k$. 

1. Construct a table (as below) and a column chart to summarize the results of the UK labour productivity growth accounting over the full sample period and each subperiod (see the video in PWT Excel tutorial - Section 7.4 for how to construct the column chart).

1. Repeat 1 to 5 for the US using the same subperiods. Compare the growth accounting results in the two countries.

1. (optional) Repeat 1 to 6 using the the average of the "labsh" variable to obtain an estimate of the elasticity of capital $\beta$. Under what assumption is this a valid method of estimation for $\beta$? How do the results change when using this alternative measure of $\beta$?

|                 | gy   |  bgk | gA   | 
|:---------------:|:----:|:----:|:----:|
|1950-2019        |      |      |      |
|First subperiod  |      |      |      |
|Second subperiod |      |      |      |
|Third subperiod  |      |      |      |


### Part 4: Sources of changes in labour productivity {-}

*This will be covered in the class if time permits.*

Based on your results in the previous part, investigate the possible underlying causes explaining the differences in **capital accumulation** and **TFP growth** between the two countries over the full sample period or in some subperiod. 

These underlying causes may refer to differences in economic or political context (eg the UK faced higher reconstruction costs than the US in 1950), differences in household behaviour, differences in policies, ...

**Can you identify one or two arguments to explain some differences in labour productivity growth trends you have identified in Part 3 between the UK and the UK? Can you provide one or two academic sources providing support to these arguments?**

To address this question, you may use these two resources:

1. The **university library** contains the most extensive database of academic papers at your disposal. Click on this (link)[https://bristol.libguides.com/economics] to start exploring.
1. You may use **Copilot** as a starting point. A useful prompt: "Can you provide 5 differences between the United Kingdom and the United States which may be related to the wider economic context, policies or the behaviour of households which may explain the lower capital accumulation of capital stock per worker in the US relative to the UK between 1950 and 1973? Can you provide detailed academic sources in support of each argument you make in this answer?" Retain only the most promising arguments and check the sources!



## Appendix: Growth accounting derivation

*In this appendix, we go into more detail into the derivation of the growth accounting equation to highlight the role of key assumptions.*

In order to structure our investigation of the relative contributions of the factor inputs to the growth of output, we need to use a theoretical framework to organise our thoughts. Whether the results of a growth accounting provides a good picture of the growth experience of a country over a given period depends on how good an approximation of the context of a country in a given period of time these assumptions are.

<br>
**Assumption 1**: Production in the economy is well represented by the following aggregate production function: 
$$Y_t=z_tF(K_t,N_t)$$
<br>

where $Y_t$ is Real GDP, $K_t$ is the capital stock (structures, transport and communication equipment, computers, software, machinery, ...), $N_t$ is the quantity of labour input (measured in number of workers, number of hours worked, hours worked adjusted for labour quality, ...) and $z_t$ is the stock of technology (may capture technological progress, the allocation of resources in the economy, the organisation of labour and management practices, ...). Note that all variables are a function of time (they have a time subscript $t$).

To find an expression for the growth rate of output as a function of the growth rate of capital, labour and technology, we first take the logarithm of the production function:
$$\log{Y_t}=\log{\left[z_tF(K_t,N_t)\right]}$$

Next, differentiate with respect to time:
$$\frac{d\log{Y_t}}{dt}=\frac{d\log{\left[z_tF(K_t,N_t)\right]}}{dt}$$
Using the fact that $\frac{d\log{X_t}}{dt}=\frac{1}{X}\frac{dX_t}{dt}$ and $\dot{X}=\frac{dX_t}{dt}$ and ignoring the time subscripts:

$$\frac{\dot{Y}}{Y}=\frac{1}{Y}\left[\frac{\partial Y}{\partial z}\dot{z}+\frac{\partial Y}{\partial K}\dot{K}+\frac{\partial Y}{\partial N}\dot{N}\right]$$

$$\frac{\dot{Y}}{Y}=\frac{\partial Y}{\partial z}\frac{z}{Y}\frac{\dot{z}}{z}+\frac{\partial Y}{\partial K}\frac{K}{Y}\frac{\dot{K}}{K}+\frac{\partial Y}{\partial N}\frac{N}{Y}\frac{\dot{N}}{N}$$
which simplifies to:
$$\frac{\dot{Y}}{Y}=\frac{\dot{z}}{z}+MPK\times \frac{K}{Y}\frac{\dot{K}}{K}+MPN\times \frac{N}{Y}\frac{\dot{N}}{N}$$

Finally, using the fact the growth rate of any variable $X$ is given by $g_X=\frac{\dot{X}}{X}$, we derive the **growth accounting equation**:
$$g_Y=g+w_Kg_K+w_Ng_N$$
where $g_Y$ is the growth rate of $Y$, $g_K$ is the growth rate of $K$ and $g_N$ is the growth rate of $N$, $w_K=\frac{K}{Y}MPK$ and $w_N=\frac{L}{N}MPN$. 

This expression states that the growth rate of $Y$ can be decomposed into the the sum of the contribution of capital accumulation $w_Kg_K$, the contribution of the growth of the labour force $w_Ng_N$ and the contribution of TFP growth $g$.

**Estimation**
<br>

**Assumption 2**: the production function $F$ exhibits constant returns to scale (CRS).This ensures the following property: $MPK \times K+MPN \times N=Y$ or $w_N+w_K=1$.

<br>
**Assumption 3**: factor (capital and labour) markets are perfectly competitive. This means that the remuneration of each input is equal to their marginal product. 
<br>

Let $R$ be the rental rate of capital and $w$ be the wage received in exchange for labour. The assumption of perfect competition implies that: 
$$R=MPK$$

$$w=MPN$$


Substituting these expressions into the expressions for $w_K$ and $w_N$:
$$w_K=\frac{K}{Y}MPK=\frac{RK}{Y}$$ 


$$w_N=\frac{N}{Y}MPN=\frac{wN}{Y}$$

where $\frac{RK}{Y}$ is the **share of capital income** and $\frac{wN}{Y}$ is the **share of labour income** in the total income.

**Remark**

If the assumption of perfect competition does not hold (for example because of the presence of externalities, distortions in the factor markets,...), we would not be able to interpret $g$ as a measure of productivity growth and this methodology would be invalid. Other methods can be used to estimate $w_K$ and $w_N$.


