# Coursework 2 Guidance {#CW2}

-------------------------------------------------------------------------------------

The aim of this chapter is to:

- Explain in more detail the tasks you are expected to perform in Coursework 2 (**due 28th April 2025**).
- (**OPTIONAL**) Propose some prompts that can be used to help large language models (eg Copilot) *assist* you in preparing and writing Coursework 2. *If you have any doubt regarding the output of a chatbot, you should ask your class tutor or post a question on the discussion board*.

To make the best of the information in this chapter, make sure that:

- You are aware of all that has been discussed in the course in Weeks 17 to 23.
- You have read carefully the Coursework Brief 2 (Blackboard --> Assessment, Submission and Feedback).
- You have looked at the Coursework 2 example (Blackboard --> Learning material --> Coursework 2 Preparation).

-------------------------------------------------------------------------------------

*Alongside more detailed guidance on how to perform Coursework 2 tasks, this chapter propose some Copilot prompts (using the example of Japan's 1990s slump) which you may use to help you get started at different stages of your coursework.* **_The use of these prompts is entirely optional. You do not need to use them to complete the coursework_**.  

*If you choose to do so, a few remarks regarding the use of large language models*: 

- **_You may use large language models (Microsoft Copilot, ChatGPT, …) to assist you through the completion of the coursework_**. 
- *Large language models are only useful to the extent that 1) you have achieved sufficient prior knowledge and understanding of the content covered in the course and any reading you may use and that 2) you understand what you are expected to do*.
- *Large language models may give you incorrect information. Do not use the ideas generated by them uncritically. However, they may provide useful starting points and come up with ideas you have not thought about or that you have missed*. 
- **_You should not copy the text generated by large language models into your analysis_**. 


## Step 1: Business Cycle Event selection {-}

Do not choose randomly a business cycle event. **Select an event**:

**1. Satisfying the conditions stated in *Selection of business cycle event* (Coursework 2 brief). This event**: 

  - may be common to several countries, but the focus should be on one country. The country must be an OECD country.
  - must be a period of macroeconomic instability where output is below/above potential output and / or unemployment is above / below the natural rate of unemployment and / or inflation is not on target and / or unemployment is above / below the natural rate of unemployment. 
  - may have a permanent effect on the long-run trends of these variables but this should not be the primary focus of the analysis.
  - should not be the Japan’s slump of the 1990s, the UK Barber’s boom of the 1970s or the US 2001 recession.
  
**2. Relatively easy to identify (at least one remarkable characteristic)**. For example, GDP growth fell very strongly, inflation was very high/low, the recovery (from a recession) was relatively slow / fast, it posed a new challenge to policymaking and/or led to the implementation of unconventional fiscal or monetary policies.

**3. For which it is easy to find data**. You are more likely to find good data if the event has taken place over the last *25 years*.

**4. From which it is possible to draw some general lessons for the future**.

**5. You find interesting**, for example because you have a personal connection to it or because you read / heard about it in the media (make it more enjoyable to you!)

**_Copilot Prompt_**:

> I am preparing an assignment for my intermediate macroeconomics course. I have been tasked with selecting a business cycle event and to analyse it using a standard macroeconomic model of business cycle fluctuations. I would like you to assist me in the choice of the business cycle event I should study. I will give you a list of criteria and you will give me 5 possible events that fit these criteria. For each, justify how the event fits each of the criteria. Here is the list of criteria: [*Insert list of criteria from above*]

**Follow-up prompt**: 

> This is good. Can you given me a list of 10 other business cycle events that also fit the criteria but that are taking place in a smaller OECD economy?


## Step 2: Literature research {-}

Before researching the literature, make sure that you can easily access data for this country. 

Search for academic references discussing the selected event:
	
1. Papers should be written by economists working either in academia or in an international organisation. Examples of relevant, accessible economic journals / reports: *Journal of Economic Perspectives*, *Bank for International Settlements BIS Papers*, *IMF working papers*, …
1. Select at most **2-3 papers** to exploit in the main analysis. You only need to discuss 2-3 good arguments. 
1. Read / skim through the papers and look for i) exogenous shocks that caused changes to GDP/ inflation (eg fall in asset prices), ii) key variables affected during the event (eg investment collapse in Japan) and iii) key mechanisms advanced to explain how the event unfolded (eg banking system crisis and phenomenon of zombie firms in Japan during the lost decade)

**_Copilot Prompt_**:

> Can you give the reference for 5 academic papers discussing the Japanese slump of the 1990s or Japan's lost decade published in Economic journals or by economics in an international organisation such as the OECD, the IMF or the world bank. Provide detailed references and if possible links to websites here the papers can be downloaded.

**_Remarks_**: 

- Large language models (chatbots) tend to “hallucinate” references.
- The more you ask for precise details regarding the publication (such as links and complete references) the less likely it is that large language models will make up the references


## Step 3: Identification of Business Cycle event {-}

**A good identification motivates clearly which characteristics of the business cycle event are important and find creative ways of conveying the information by plotting it**. 

**Based on your understanding of the event (and what made it special), identify the most important variables to represent in 4 different figures **:

1. GDP growth and inflation.
1. Key components of aggregate demand or aggregate supply affected during the event (consumption, investment labour productivity, ...).
1. Key labour market (employment / unemployment, wages) and credit market (quantity of credit, interest rates) variables.
1. One figure may represent more than one variable. Ideally the variables represented in the same figure should allow for a meaningful comparisons (eg it makes more sense to represent consumption on the same plot as GDP and investment than consumption on the same plot as the unemployment rate).


**Collect data and construct 4 figures**:

1. The FRED database is a good starting point. The OECD Data explorer, the IMF International Financial Statistics and World Bank Open Data may provide useful complementary data.
1. In this section, all the figures should be constructed by you using data collected on official websites. Avoid copying figures from websites. 
1. The data you collect and represent will usually be at the monthly or quarterly frequency. If your event is a recession, then you should discuss in more detail what happened to quarterly GDP growth.
1. Think about the best way to describe what happened during your event:

  - *Indexing variables* to a common starting point is a useful tool to compare what happened to two or more variables following a demand/supply shock.
  - Using a *secondary axis* when representing two variables on the same plot.


**The aim of this section should be to**:

- Describe what happened to the key (endogenous) macroeconomic variables during the event (GDP, Consumption, investment, unemployment, inflation, wage, interest rates), **not** to explain what happened. Highlight what made this particular business cycle event special. 
- Discuss, based on the information presented, whether the event was caused by a demand or a supply shock (eg a fall in economic activity associated with a fall in inflation suggests that a negative aggregate demand shock hit the economy). However, avoid discussing the shocks that caused the event in detail this section.


**_Copilot Prompt_**:

> I am studying Japan's slump of the 1990s. I would like to describe the key feature of this event in 4 data plots which may represent more than one variable each. Can you suggest to me the variables that would help me best characterise what happened at the macroeconomic level during this episode in four different plots? The focus should be on variables that are endogenous in simple intermediate macroeconomic models: consumption, investment, unemployment, GDP, real and nominal interest rates, real and nominal wages.

## Step 4: Main analysis {-}

**1. Identify (exogenous) shocks**:

- The shock cannot be to an endogenous variable in the 3-equation model (output, consumption, investment, interest rate, inflation, wage, unemployment). For example, a change in consumption (C) cannot be explained by a shock to income (y). Although a change in income may lead to a change in consumption, a change in consumption may also lead to a change in income in the model. You need to identify the initial (external) source of the shock that caused changes in both variables. 
- The more precisely the shock is identified the better. It is not enough to write that “there is a negative shock to the banking system”; to be more precise, you may explain that the shock was caused by a fall in asset prices, a rise in the number of non-performing loans, a rise in interest rates, a change in regulation, …. 
- You may use figures (eg data plot) or key numbers to illustrate the identification the shocks.

**2. Explanation: explain what happens to endogenous variables following the exogenous shocks**

- **Identify which relationship in the 3-equation model (as well as consumption and investment theory, models of credit constraints, QE, …) is affected by the shock**. For example, a shock to stock prices may affect autonomous investment (a parameter of the IS curve), leading to a shift of the IS curve. 
- **Higher level explanations: how do we derive the intuition from economic models?** Economic models usually explain changes in outcomes (output, inflation, interest rate, …) as the result of the interactions between agents (households, firms, banks, policymakers, …) who are attempting to maximize an objective subject to some constraints (resources, beliefs, lags, regulations, credit market imperfections, …). The solution to each agent’s problem gives rise to some trade-offs (eg marginal benefit versus marginal cost for households and firms, inflation versus unemployment for policymakers, arbitrage between different assets for investors). These provide the intuition to explain changes in their behaviour following shocks. A good explanation will usually explain or hint at the relevant trade-offs (using the relevant optimality conditions and / or diagrams) and discuss what happens to it following a shock. For example, you may use investment theories to explain in more detail why autonomous investment changes following a shock to stock prices. If the shock affects expected future profits, then the optimality condition MPK = user cost can help explain the change in autonomous investment. If the shock affects credit market constraints, then a balance sheet model (eg Stiglitz and Weiss) can help explain the change in autonomous investment.

**3. Evaluation**: 

- Compare the predictions of the model with what happened to the endogenous variables (Section 2). What can the theory explain? What cannot be explained by the theory?
- You may want to discuss the reason why a fact cannot be explained by the model employed. By definition, economic models are simplifications of the reality. Avoid making general statements such as “the model is too simple and not realistic”. A better evaluation would argue more precisely which assumption is likely to be at fault (eg the way expectations are formulated, timing assumptions, …). For example, the presence of credit market constraints may lead to a failure of the optimality condition MPK=user cost, which is derived by assuming the absence of credit market imperfections. 

**_Copilot Prompt_: Identifying shocks**:

> I am studying Japan's slump of the 1990s. I know that the slump was initiated by a fall in asset prices (Ueda, 2012), especially stock prices and land prices. Can you suggest 5 possible methods I could use to convey the importance and the magnitude of the shock using data plots or key event illustrating the significance of the shock to asset price. In each case, provide detailed information regarding where I can find the data or the relevant economics publication analysing the event.

**_Remarks_**: 

- Providing an example of a “good” source of information (eg Ueda, 2012) indicates to large language models what constitutes a valid source and help it focus attention on the most relevant type of (academic) sources.
- Some links provided by large language models may not exist or may no longer exist.  

**_Follow-up prompt_**:

> Regarding the last item (bank balance sheet and non-performing loans), could you provide more detailed references to the sources, including links to websites where the paper or the data can be collected?

**_Copilot Prompt_: Identify key economic mechanisms**

Ueda, K. (2012), “Deleveraging and monetary policy: Japan since the 1990s and the United States since 2007”, Journal of Economics perspectives **[attach]**

> Can you summarize the 3 main ideas regarding the Japan experience in the 1990s developed in the article attached. For each ideas explain the key economic reasoning and mechanism at play in the Japanese economy at the time.

**_Copilot Prompt_: Explanation and evaluation: how can consumption and investment theory help us think about a macroeconomic event?**

> I want to explain the fall in investment in Japan in the early 1990s using the simple optimality condition that firms invest up to the point where the marginal benefit of investing in an additional unit of capital is equal to its user cost. Explain to me what insight the theory provides that a naive discussion would have missed.

**_Copilot Prompt_: Explanation: Carlin and Soskice 3-equation model**

*Avoid asking a large language model to illustrate the effect of a shock in the Carlin and Soskice 3-equation model discussed in the course. It usually comes up with very incorrect answers. You will have to figure that out on your own! However, large language model can explain the broad intuition provided by the model in imprecise terms.*

**_Copilot Prompt_: General feedback**

*You may ask large language models for feedback. As always, this should not always be taken at face value. However, it may highlight obvious mistakes and omissions much as the feedback provided by one of your peers.*

> I am going to give you a paragraph explaining how the burst in the asset price bubble in Japan in 1990 led to a fall in investment. I want you to give me feedback as if you were a university lecturer in Economics focusing on 1) any possible mistake in the explanations, 2) any missing argument / information, 3) any incoherence in the economic reasoning and 4) any possible criticism of the arguments (not because they are incorrect but because other theories would yield different predictions). [Insert paragraph]


## Step 5: Research question {-}

- Follow the instructions in the coursework brief and look at the example.
- This section may be completed at the end. This is to ensure that your research question is the one you are addressing in your analysis. More often than not, your research question will change over time as your arguments become clearer.
- Avoid making general statements and be precise. 


